trigger:
- master

pool:
  name: Test  

steps:
- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/java-17-openjdk-amd64"
    echo "##vso[task.setvariable variable=PATH]$JAVA_HOME/bin:$PATH"
    java -version
  displayName: 'Set JAVA_HOME manually'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path' 
    jdkUserInputPath: '/usr/lib/jvm/java-17-openjdk-amd64' # Use system-installed Java
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'Sontype_Test'
    applicationId: 'demo_app'
    stage: 'Build'
    scanTargets: '**/target/*.jar'
