trigger:
- master

pool:
  name: OCI_ARM_Machine  # Updated to your new agent pool

steps:
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'  # Ensure Java 17 is used
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: NexusIqPipelineTask@2
  inputs:
    nexusIqService: 'Sontype_Test'
    applicationId: 'demo_app'
    stage: 'Build'
    scanTargets: '**/target/*.jar'
